### ISSUE TITLE
Crash when entering the dimension

### ISSUE THREAD

**Issue by Shuisho10** [Quantum64/Stars#2]
When entering the gateway, i randomly crash

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 10/3/19 8:11 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraftforge.common.DimensionManager$SavedEntry.write(DimensionManager.java:497) ~[?:?] {re:classloading}
	at net.minecraftforge.common.DimensionManager$SavedEntry.access$500(DimensionManager.java:438) ~[?:?] {re:classloading}
	at net.minecraftforge.common.DimensionManager.lambda$writeRegistry$3(DimensionManager.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.common.DimensionManager$$Lambda$3939/169456954.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.common.DimensionManager.writeRegistry(DimensionManager.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeMod.getDataForWriting(ForgeMod.java:156) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks.lambda$handleWorldDataSave$0(WorldPersistenceHooks.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks$$Lambda$3936/1436257722.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.WorldPersistenceHooks.handleWorldDataSave(WorldPersistenceHooks.java:40) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:53) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:525) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:107) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556244728 bytes (530 MB) / 1567096832 bytes (1494 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3072m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.31
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		stars-1.0.5.jar Stars {stars@1.0.5 DONE}
		forge-1.14.4-28.1.31-universal.jar Forge {forge@28.1.31 DONE}
		forge-1.14.4-28.1.31-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Shuisho10'/1, l='New World', x=0.50, y=105.00, z=0.50]]
	Data Packs: vanilla, mod:stars, mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Shuisho10** [comment]
Update: The error is produced in Forge-28.1.31, meanwhile in version Forge-28.1.20 it works just fine!

**Comment by Quantum64** [comment]
Hm. Looks like it's possibly a purely forge issue. Can you check if it still happens in forge 28.1.39?
